# Conclusion


*Summary: Crimes Analysis*

We looked at a stacked bar graph with crime counts over time for all boroughs, which showed fluctuations in crime rates over time. To analyze seasonality further, we created a heatmap with crime dates by quarter, which showed more clearly that 3Q tends to have higher crime rates. Next, we analyzed total crime rates for each borough individually, which showed that the trends in crimes show an increasing trend from 2015 to 2019, followed by declines during the pandemic, followed by increases through 2023 with a tendency to surpass the previous crime records (except for the Bronx). To analyze the data by crime type, we generated line graphs with trends in each of the 7 types of crime over time for each borough, which highlighted robbery and grand larceny as two of the most frequent crimes. Then, we examined a potential correlation between the number of crimes at park based on the size of the park, and saw that there was no distinct upward trend line that would indicate a clear positive correlation between park size and crime rates.

*Summary: Unemployment Correlations*

We plotted a line graph showing a time series of unemployment rates from 2013-2023. We included a trend line to see how rates have changed over time. Then, we created similar graphs for crime rates showing their respective trend lines over time for each borough. Generally, we found that the trends were the opposite between the two sets of data, highlighting that crime is lower during periods of higher unemployment. We note correlation does not mean causation.

*Summary: Mobility data*

We used pandemic-period Google Mobility data to see the trends in park visits over a 2 year time frame for all 5 boroughs. We saw that the greatest relative increase in park visits was seen in Queens and the smallest relative increase was in Manhattan. We the summarized the total number of parks in each borough, and found that the number of parks were not indicative of the trends in park visits. Lastly, we noted the trends in park visits for each borough and generated crime rate graphs for the same time period to compare. At a high level, we noted similarities in trends.

*Limitations*

Our data on crimes was limited in that it was provided on a quarterly basis, which means that we were unable to derive any insights into what month each month in particular may have contributed towards the crime rate. Additionally, we had no information on the nature of the crimes themselves. For example, what time the crime took place? Was the perpetrator a repeat offender? Our data on unemployment rates was also limited in that it was an overall rate for NY, and not broken down by each borough. Such detail would have improved the granularity of our analysis in that we would be able to examine the unemployment rate for each borough individually. Our mobility data had several limitations, such as only being available for a 2 year period and showing relative values to pre-pandemic instead of absolute visit numbers. If a certain borough had robust park utilization before the pandemic, their relative increase in visits is expected to be minimal while any decreases might be more pronounced. Additionally, the data was not available directly from the source since it is published in a pdf report, which means that excel data exports would either have to be scraped from scratch or pulled from an existing scrape, as we did from a Github repo.

*Future Directions*

In the future, we may consider the impact of other factors on crimes at parks. For example, we look at levels of policing in different boroughs and the impact of income levels. Another economic factor that we could look at is discretionary spending and personal savings - if discretionary spending declines, there may be more park visits, and consequently crime rates may rise. 

